### ISSUE TITLE
IE11 and Edge Background Jumpy Glitch

### ISSUE THREAD

**Issue by joe-replin** [cgkineo/adapt-backgroundSwitcher#23]
![wd2](https://user-images.githubusercontent.com/7740674/41163342-099de9e4-6afe-11e8-80fb-28b91f394490.gif)

IE and Edge's smooth-scrolling feature seems to have brought an undesirable effect on backgrounds that are set to fixed positions with full coverage. I've applied the following function after researching this fix for a bit. This will bypass the smooth scrolling feature and keep the fixed background in place on IE. I call this function within the onPageReady function.

		disableSmoothScrolling: function() {
			if(navigator.userAgent.match(/Trident\/7\./)) { // if IE
			    $('.background-switcher-container').on("mousewheel", function (event) {
			        // remove default behavior
			        event.preventDefault(); 

			        //scroll without smoothing
			        var wheelDelta = event.wheelDelta;
			        var currentScrollPosition = window.pageYOffset;
			        window.scrollTo(0, currentScrollPosition - wheelDelta);
			    });
			}  
		},

**Comment by moloko** [comment]
interesting, thanks for sharing!

**Comment by oliverfoster** [comment]
fixed
