### ISSUE TITLE
AT block editing error

### ISSUE THREAD

**Issue by barryjenkin** [cgkineo/adapt-backgroundSwitcher#47]
Hi there.
Just having issues using this with AT 0.10.5 and FW 5.22.3
When installed (whether page-enabled or not) it prevents loading of AT editor at block level.  

<img width="1372" alt="Screen Shot 2022-09-07 at 3 47 26 pm" src="https://user-images.githubusercontent.com/24560844/188798386-6dfef1b6-446f-4bed-b07e-c4a27e10da5a.png">

**Comment by sebj8** [comment]
I have the same issue with current version.
